### PR TITLE
Disable kernel injection when using CPUs

### PR DESCRIPTION
**Pull request by foin6**
There added a new argument to control whether enable kernel injection or not, so that the code will run properly on the CPUs.

### CODE REVIEW

**Comment by delock** [comment]
I have two comments.

1. This new switch change the default behavior (absence of this switch would turn off kernel injection).  So existing scripts will have behavior change which may not be desired.

2. We should not check device name here, I think a simple switch to turn off kernel injection should be sufficient.

**Comment by foin6** [comment]
> I have two comments.
> 
> 1. This new switch change the default behavior (absence of this switch would turn off kernel injection).  So existing scripts will have behavior change which may not be desired.
> 2. We should not check device name here, I think a simple switch to turn off kernel injection should be sufficient.

@delock OK. But if we enable kernel injection by default as the original code does, the code cannot run properly on CPUs. So, do we need to also modify the corresponding content of the README file to notify users to disable kernel injection with the new argument when running on CPUs?

**Comment by delock** [comment]
CPU does not work without kernel injection is an expected behavior.  It's okay if we put a note in README file to remind user turn of kernel injection when using CPU.

**Comment by delock** [comment]
I found one issue with this test that when running the test with num_gpus=2, there will be 2 baseline inference runing inside each rank.  Actually only one inference will be needed on rank 0 and the comparison can be done on rank 0.  Can you check rank and do the comparison on rank0 only?

**Pull request closed without merging**
